# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=50)),
                ('Phone', models.IntegerField(max_length=20)),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('Country', models.CharField(max_length=20)),
            ],
        ),
    ]
