# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20171219_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='image',
            field=models.ImageField(default='media/default.jpg', upload_to='contact_images'),
        ),
    ]
